config/routes.rb
SoExample::Application.routes.draw do
  namespace :self_service do resources :customers end

end

app/models/self_service.rb
module SelfService
  def self.table_name_prefix
    'self_service_'
  end
end

app/models/self_service/customer.rb
class SelfService::Customer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/self_service/customers_controller.rb
class SelfService::CustomersController < ApplicationController
  # GET /self_service/customers
  # GET /self_service/customers.xml
  def index
    @self_service_customers = SelfService::Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @self_service_customers }
    end
  end

  # GET /self_service/customers/1
  # GET /self_service/customers/1.xml
  def show
    @self_service_customer = SelfService::Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @self_service_customer }
    end
  end

  # GET /self_service/customers/new
  # GET /self_service/customers/new.xml
  def new
    @self_service_customer = SelfService::Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @self_service_customer }
    end
  end

  # GET /self_service/customers/1/edit
  def edit
    @self_service_customer = SelfService::Customer.find(params[:id])
  end

  # POST /self_service/customers
  # POST /self_service/customers.xml
  def create
    @self_service_customer = SelfService::Customer.new(params[:self_service_customer])

    respond_to do |format|
      if @self_service_customer.save
        format.html { redirect_to(@self_service_customer, :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @self_service_customer, :status => :created, :location => @self_service_customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @self_service_customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /self_service/customers/1
  # PUT /self_service/customers/1.xml
  def update
    @self_service_customer = SelfService::Customer.find(params[:id])

    respond_to do |format|
      if @self_service_customer.update_attributes(params[:self_service_customer])
        format.html { redirect_to(@self_service_customer, :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @self_service_customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /self_service/customers/1
  # DELETE /self_service/customers/1.xml
  def destroy
    @self_service_customer = SelfService::Customer.find(params[:id])
    @self_service_customer.destroy

    respond_to do |format|
      format.html { redirect_to(self_service_customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/self_service/customers_helper.rb
module SelfService::CustomersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/self_service/customers/_form.html.erb
<%= form_for(@self_service_customer) do |f| %>
  <% if @self_service_customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@self_service_customer.errors.count, "error") %> prohibited this self_service_customer from being saved:</h2>

      <ul>
      <% @self_service_customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/self_service/customers/edit.html.erb
<h1>Editing self_service_customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @self_service_customer %> |
<%= link_to 'Back', self_service_customers_path %>

app/views/self_service/customers/index.html.erb
<h1>Listing self_service_customers</h1>

<table>
  <tr>
    <th>String</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @self_service_customers.each do |self_service_customer| %>
  <tr>
    <td><%= self_service_customer.string %></td>
    <td><%= link_to 'Show', self_service_customer %></td>
    <td><%= link_to 'Edit', edit_self_service_customer_path(self_service_customer) %></td>
    <td><%= link_to 'Destroy', self_service_customer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_self_service_customer_path %>

app/views/self_service/customers/new.html.erb
<h1>New self_service_customer</h1>

<%= render 'form' %>

<%= link_to 'Back', self_service_customers_path %>

app/views/self_service/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>String:</b>
  <%= @self_service_customer.string %>
</p>


<%= link_to 'Edit', edit_self_service_customer_path(@self_service_customer) %> |
<%= link_to 'Back', self_service_customers_path %>